// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasteCollectionPlatform.Common.Enums;
using WasteCollectionPlatform.DataAccess.Context;

#nullable disable

namespace WasteCollectionPlatform.DataAccess.Migrations
{
    [DbContext(typeof(WasteManagementContext))]
    [Migration("20260306124956_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "image_type", new[] { "Citizen", "Collector" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "point_transaction_type", new[] { "Earn", "Redeem" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "report_status", new[] { "Pending", "Accepted", "Assigned", "OnTheWay", "Collected", "Failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "team_type", new[] { "Main", "Support" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "citizen", "collector", "enterprise", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Area", b =>
                {
                    b.Property<int>("Areaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("areaid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Areaid"));

                    b.Property<int>("Districtid")
                        .HasColumnType("integer")
                        .HasColumnName("districtid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Areaid")
                        .HasName("area_pkey");

                    b.HasIndex("Districtid");

                    b.ToTable("area", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Citizen", b =>
                {
                    b.Property<int>("Citizenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("citizenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Citizenid"));

                    b.Property<int?>("Totalpoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("totalpoints");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Citizenid")
                        .HasName("citizen_pkey");

                    b.HasIndex(new[] { "Userid" }, "citizen_userid_key")
                        .IsUnique();

                    b.ToTable("citizen", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Collector", b =>
                {
                    b.Property<int>("Collectorid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("collectorid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Collectorid"));

                    b.Property<int?>("Currenttaskcount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("currenttaskcount");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Collectorid")
                        .HasName("collector_pkey");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "Userid" }, "collector_userid_key")
                        .IsUnique();

                    b.ToTable("collector", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.District", b =>
                {
                    b.Property<int>("Districtid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("districtid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Districtid"));

                    b.Property<string>("Districtname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("districtname");

                    b.HasKey("Districtid")
                        .HasName("district_pkey");

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Enterprise", b =>
                {
                    b.Property<int>("Enterpriseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enterpriseid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Enterpriseid"));

                    b.Property<int?>("Currentload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("currentload");

                    b.Property<int?>("Dailycapacity")
                        .HasColumnType("integer")
                        .HasColumnName("dailycapacity");

                    b.Property<int?>("Districtid")
                        .HasColumnType("integer")
                        .HasColumnName("districtid");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Wastetypes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wastetypes");

                    b.HasKey("Enterpriseid")
                        .HasName("enterprise_pkey");

                    b.HasIndex("Districtid");

                    b.HasIndex(new[] { "Userid" }, "enterprise_userid_key")
                        .IsUnique();

                    b.ToTable("enterprise", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("Notificationid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Notificationid"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Isread")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int?>("Reportid")
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Notificationid")
                        .HasName("notification_pkey");

                    b.HasIndex("Reportid");

                    b.HasIndex("Userid");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Pointhistory", b =>
                {
                    b.Property<int>("Pointlogid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pointlogid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pointlogid"));

                    b.Property<int>("Citizenid")
                        .HasColumnType("integer")
                        .HasColumnName("citizenid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Pointamount")
                        .HasColumnType("integer")
                        .HasColumnName("pointamount");

                    b.Property<int?>("Reportid")
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    b.Property<int?>("Voucherid")
                        .HasColumnType("integer")
                        .HasColumnName("voucherid");

                    b.HasKey("Pointlogid")
                        .HasName("pointhistory_pkey");

                    b.HasIndex("Citizenid");

                    b.HasIndex("Reportid");

                    b.HasIndex("Voucherid");

                    b.ToTable("pointhistory", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Refreshtokenid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("refreshtokenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Refreshtokenid"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Expiresat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<bool?>("Isrevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isrevoked");

                    b.Property<DateTime?>("Revokedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Refreshtokenid")
                        .HasName("refreshtoken_pkey");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refreshtoken_token");

                    b.HasIndex("Userid")
                        .HasDatabaseName("idx_refreshtoken_userid");

                    b.ToTable("refreshtoken", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Reportassignment", b =>
                {
                    b.Property<int>("Assignmentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("assignmentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Assignmentid"));

                    b.Property<int>("Reportid")
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    b.HasKey("Assignmentid")
                        .HasName("reportassignment_pkey");

                    b.HasIndex("Reportid");

                    b.HasIndex("TeamId");

                    b.ToTable("reportassignment", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Reportimage", b =>
                {
                    b.Property<int>("Imageid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("imageid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Imageid"));

                    b.Property<string>("Imageurl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imageurl");

                    b.Property<int>("Reportid")
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    b.HasKey("Imageid")
                        .HasName("reportimage_pkey");

                    b.HasIndex("Reportid");

                    b.ToTable("reportimage", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teamid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<int>("Areaid")
                        .HasColumnType("integer")
                        .HasColumnName("areaid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("TeamId")
                        .HasName("team_pkey");

                    b.HasIndex("Areaid");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("Emailverified")
                        .HasColumnType("boolean")
                        .HasColumnName("emailverified");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fullname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Resetpasswordtoken")
                        .HasColumnType("text")
                        .HasColumnName("resetpasswordtoken");

                    b.Property<DateTime?>("Resettokenexpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resettokenexpiry");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<string>("Verificationtoken")
                        .HasColumnType("text")
                        .HasColumnName("verificationtoken");

                    b.Property<DateTime?>("Verificationtokenexpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verificationtokenexpiry");

                    b.HasKey("Userid")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "Email" }, "User_email_key")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Voucher", b =>
                {
                    b.Property<int>("Voucherid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("voucherid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Voucherid"));

                    b.Property<int>("Pointsrequired")
                        .HasColumnType("integer")
                        .HasColumnName("pointsrequired");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<int>("Stockquantity")
                        .HasColumnType("integer")
                        .HasColumnName("stockquantity");

                    b.Property<string>("Vouchername")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vouchername");

                    b.HasKey("Voucherid")
                        .HasName("voucher_pkey");

                    b.ToTable("voucher", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Wastereport", b =>
                {
                    b.Property<int>("Reportid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("reportid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Reportid"));

                    b.Property<int>("Areaid")
                        .HasColumnType("integer")
                        .HasColumnName("areaid");

                    b.Property<int>("Citizenid")
                        .HasColumnType("integer")
                        .HasColumnName("citizenid");

                    b.Property<decimal?>("Citizenlatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("citizenlatitude");

                    b.Property<decimal?>("Citizenlongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("citizenlongitude");

                    b.Property<decimal?>("Collectorlatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("collectorlatitude");

                    b.Property<decimal?>("Collectorlongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("collectorlongitude");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("Expiretime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiretime");

                    b.Property<string>("Wastetype")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wastetype");

                    b.HasKey("Reportid")
                        .HasName("wastereport_pkey");

                    b.HasIndex("Areaid");

                    b.HasIndex("Citizenid");

                    b.ToTable("wastereport", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Area", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.District", "District")
                        .WithMany("Areas")
                        .HasForeignKey("Districtid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_area_district");

                    b.Navigation("District");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Citizen", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne("Citizen")
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Citizen", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_citizen_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Collector", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Team", "Team")
                        .WithMany("Collectors")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collector_team");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne("Collector")
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Collector", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collector_user");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Enterprise", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("Districtid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_enterprise_district");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Enterprise", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enterprise_user");

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Wastereport", "Report")
                        .WithMany("Notifications")
                        .HasForeignKey("Reportid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_report");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Pointhistory", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Citizen", "Citizen")
                        .WithMany("Pointhistories")
                        .HasForeignKey("Citizenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_citizen");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Wastereport", "Report")
                        .WithMany("Pointhistories")
                        .HasForeignKey("Reportid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_point_report");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Voucher", "Voucher")
                        .WithMany("Pointhistories")
                        .HasForeignKey("Voucherid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_point_voucher");

                    b.Navigation("Citizen");

                    b.Navigation("Report");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.RefreshToken", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtoken_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Reportassignment", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Wastereport", "Report")
                        .WithMany("Reportassignments")
                        .HasForeignKey("Reportid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_report");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Team", "Team")
                        .WithMany("Reportassignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_team");

                    b.Navigation("Report");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Reportimage", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Wastereport", "Report")
                        .WithMany("Reportimages")
                        .HasForeignKey("Reportid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_report");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Team", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Area", "Area")
                        .WithMany("Teams")
                        .HasForeignKey("Areaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_area");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Wastereport", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Area", "Area")
                        .WithMany("Wastereports")
                        .HasForeignKey("Areaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_area");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Citizen", "Citizen")
                        .WithMany("Wastereports")
                        .HasForeignKey("Citizenid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_citizen");

                    b.Navigation("Area");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Area", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("Wastereports");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Citizen", b =>
                {
                    b.Navigation("Pointhistories");

                    b.Navigation("Wastereports");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.District", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Team", b =>
                {
                    b.Navigation("Collectors");

                    b.Navigation("Reportassignments");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Citizen");

                    b.Navigation("Collector");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Voucher", b =>
                {
                    b.Navigation("Pointhistories");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Wastereport", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Pointhistories");

                    b.Navigation("Reportassignments");

                    b.Navigation("Reportimages");
                });
#pragma warning restore 612, 618
        }
    }
}
