// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasteCollectionPlatform.Common.Enums;
using WasteCollectionPlatform.DataAccess.Context;

#nullable disable

namespace WasteCollectionPlatform.DataAccess.Migrations
{
    [DbContext(typeof(WasteManagementContext))]
    partial class WasteManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "collector_role", "collector_role", new[] { "member", "leader" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "image_type", new[] { "Citizen", "Collector" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "point_transaction_type", new[] { "Earn", "Redeem" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "report_status", new[] { "Pending", "Assigned", "Processing", "Completed", "Cancelled" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "team_type", new[] { "Main", "Support" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "citizen", "collector", "enterprise", "admin" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Department");

                    b.Property<bool>("IsSuperAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsSuperAdmin");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LastLoginAt");

                    b.Property<int?>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("Level");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("Id")
                        .HasName("admin_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "UserId" }, "admin_userid_key")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AreaId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AreaId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Name");

                    b.HasKey("AreaId")
                        .HasName("area_pkey");

                    b.HasIndex("DistrictId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Citizen", b =>
                {
                    b.Property<int>("CitizenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CitizenId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CitizenId"));

                    b.Property<int?>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalPoints");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("CitizenId")
                        .HasName("citizen_pkey");

                    b.HasIndex(new[] { "UserId" }, "citizen_userid_key")
                        .IsUnique();

                    b.ToTable("Citizens", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Collector", b =>
                {
                    b.Property<int>("CollectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CollectorId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CollectorId"));

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("Role");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("TeamId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("CollectorId")
                        .HasName("collector_pkey");

                    b.HasIndex("TeamId");

                    b.HasIndex(new[] { "UserId" }, "collector_userid_key")
                        .IsUnique();

                    b.ToTable("Collectors", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("DistrictId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("DistrictName");

                    b.HasKey("DistrictId")
                        .HasName("district_pkey");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Enterprise", b =>
                {
                    b.Property<int>("EnterpriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enterpriseid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("EnterpriseId"));

                    b.Property<int?>("Currentload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("currentload");

                    b.Property<int?>("Dailycapacity")
                        .HasColumnType("integer")
                        .HasColumnName("dailycapacity");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("districtid");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Wastetypes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wastetypes");

                    b.HasKey("EnterpriseId")
                        .HasName("enterprise_pkey");

                    b.HasIndex("DistrictId");

                    b.HasIndex(new[] { "UserId" }, "enterprise_userid_key")
                        .IsUnique();

                    b.ToTable("enterprise", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NotificationId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Isread")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Message");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("ReportId");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    b.HasKey("NotificationId")
                        .HasName("notification_pkey");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.PointHistory", b =>
                {
                    b.Property<int>("PointlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PointLogId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PointlogId"));

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("CitizenId");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PointAmount")
                        .HasColumnType("integer")
                        .HasColumnName("PointAmount");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("ReportId");

                    b.Property<int?>("VoucherId")
                        .HasColumnType("integer")
                        .HasColumnName("VoucherId");

                    b.HasKey("PointlogId")
                        .HasName("pointhistory_pkey");

                    b.HasIndex("CitizenId");

                    b.HasIndex("ReportId");

                    b.HasIndex("VoucherId");

                    b.ToTable("PointHistories", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<int>("RefreshtokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("refreshtokenid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("RefreshtokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Expiresat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<bool?>("Isrevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isrevoked");

                    b.Property<DateTime?>("Revokedat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("RefreshtokenId")
                        .HasName("refreshtoken_pkey");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_refreshtoken_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_refreshtoken_userid");

                    b.ToTable("refreshtoken", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.ReportAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AssignmentId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("ReportId");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("TeamId");

                    b.HasKey("AssignmentId")
                        .HasName("reportassignment_pkey");

                    b.HasIndex("ReportId");

                    b.HasIndex("TeamId");

                    b.ToTable("ReportAssignments", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.ReportImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ImageId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Imageurl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ImageUrl");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer")
                        .HasColumnName("ReportId");

                    b.HasKey("ImageId")
                        .HasName("reportimage_pkey");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportImages", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TeamId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeamId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("AreaId");

                    b.Property<int>("CurrentTaskCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("CurrentTaskCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Name");

                    b.HasKey("TeamId")
                        .HasName("team_pkey");

                    b.HasIndex("AreaId");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("Emailverified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("EmailVerified");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("FullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("Resetpasswordtoken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ResetPasswordToken");

                    b.Property<DateTime?>("Resettokenexpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ResetTokenExpiry");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("Role");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer")
                        .HasColumnName("tokenversion");

                    b.Property<string>("Verificationtoken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("VerificationToken");

                    b.Property<DateTime?>("Verificationtokenexpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("VerificationTokenExpiry");

                    b.HasKey("UserId")
                        .HasName("User_pkey");

                    b.HasIndex(new[] { "Email" }, "User_email_key")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VoucherId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoucherId"));

                    b.Property<int>("PointsRequired")
                        .HasColumnType("integer")
                        .HasColumnName("PointsRequired");

                    b.Property<bool?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Status");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("StockQuantity");

                    b.Property<string>("VoucherName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("VoucherName");

                    b.HasKey("VoucherId")
                        .HasName("voucher_pkey");

                    b.ToTable("Vouchers", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.WasteReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReportId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer")
                        .HasColumnName("AreaId");

                    b.Property<int>("CitizenId")
                        .HasColumnType("integer")
                        .HasColumnName("CitizenId");

                    b.Property<decimal?>("CitizenLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("CitizenLatitude");

                    b.Property<decimal?>("CitizenLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("CitizenLongitude");

                    b.Property<decimal?>("CollectorLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("CollectorLatitude");

                    b.Property<decimal?>("CollectorLongitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("CollectorLongitude");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("ExpireTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpireTime");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("TeamId");

                    b.Property<string>("WasteType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("WasteType");

                    b.HasKey("ReportId")
                        .HasName("wastereport_pkey");

                    b.HasIndex("AreaId");

                    b.HasIndex("CitizenId");

                    b.ToTable("WasteReports", (string)null);
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Admin", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_admin_createdby");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_user");

                    b.Navigation("CreatorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Area", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.District", "District")
                        .WithMany("Areas")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_area_district");

                    b.Navigation("District");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Citizen", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne("Citizen")
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Citizen", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_citizen_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Collector", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Team", "Team")
                        .WithMany("Collectors")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collector_team");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne("Collector")
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Collector", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collector_user");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Enterprise", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_enterprise_district");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("WasteCollectionPlatform.DataAccess.Entities.Enterprise", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enterprise_user");

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Notification", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.WasteReport", "Report")
                        .WithMany("Notifications")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notification_report");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.PointHistory", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Citizen", "Citizen")
                        .WithMany("PointHistories")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_point_citizen");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.WasteReport", "Report")
                        .WithMany("PointHistories")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_point_report");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Voucher", "Voucher")
                        .WithMany("PointHistories")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_point_voucher");

                    b.Navigation("Citizen");

                    b.Navigation("Report");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.RefreshToken", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refreshtoken_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.ReportAssignment", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.WasteReport", "Report")
                        .WithMany("ReportAssignments")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_report");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Team", "Team")
                        .WithMany("ReportAssignments")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_team");

                    b.Navigation("Report");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.ReportImage", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.WasteReport", "Report")
                        .WithMany("ReportImages")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_image_report");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Team", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Area", "Area")
                        .WithMany("Teams")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_area");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.WasteReport", b =>
                {
                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Area", "Area")
                        .WithMany("WasteReports")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_area");

                    b.HasOne("WasteCollectionPlatform.DataAccess.Entities.Citizen", "Citizen")
                        .WithMany("WasteReports")
                        .HasForeignKey("CitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_citizen");

                    b.Navigation("Area");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Area", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("WasteReports");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Citizen", b =>
                {
                    b.Navigation("PointHistories");

                    b.Navigation("WasteReports");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.District", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Team", b =>
                {
                    b.Navigation("Collectors");

                    b.Navigation("ReportAssignments");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Citizen");

                    b.Navigation("Collector");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.Voucher", b =>
                {
                    b.Navigation("PointHistories");
                });

            modelBuilder.Entity("WasteCollectionPlatform.DataAccess.Entities.WasteReport", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("PointHistories");

                    b.Navigation("ReportAssignments");

                    b.Navigation("ReportImages");
                });
#pragma warning restore 612, 618
        }
    }
}
